### ISSUE TITLE
Notification Email pour la procédure avancée

### ISSUE THREAD

**Issue by renaudham** [OlivierWizi/WiziYousignClient#1]
Il manque l'équivalent de addMemberWhithMailNotif
pour la procédure avancée

que l'on puisse aussi ajouter les infos 
$conf["email"] =
            array(
                "member.started" => array(
                    array(
                        "subject" => $mailsubject,
                        "message" => "Hello",
                        "to" => array("@member")
                    )
                ),
                "procedure.started" => array(
                    array(
                        "subject" => $mailsubject,
                        "message" => $mailMessage,
                        "to" => $arrayTo
                    )
                )
            )

        ;

via soit AdvancedProcedureAddMember
soit direct à la création
AdvancedProcedureCreate

Pour le moment j'ai modifié moi meme AdvancedProcedureCreate de mon côté....
Merci

**Comment by OlivierWizi** [comment]
Bonjour renaudham,
C'est très gentil, Tu peux récupérer le dernier pull et proposer ta modification en pr ou m'envoyer la classe modifié par mail olivier.nival@gmail.com

**Comment by OlivierWizi** [comment]
il faudra aussi que tu documentes la nouvelle fonction et que tu mettes un exemple de code qui montre un cas d'utilisation complet de ta nouvelle fonction.

**Comment by renaudham** [comment]
Bonjour

Ai je fais cet envois annoncé auparant ou nnon??

Merci


*Renaud Hamelin*
Dirigeant, CTO, et Lead développeur
Blue Origami Digital  (Sarl)
Studio solutions web et solutions Intelligence Artificielle
Conception, Consulting et Production


*Strasbourg - Paris*Skype : renaudham69
Tel : 06 37 67 46 46
Email secondaire : renaud@b-o-d.fr
Site : https://blue-origami-digital.com/
Linkedin : https://fr.linkedin.com/in/renaudhamelin
https://www.linkedin.com/company/blue-origami-digital/
FB société : https://www.facebook.com/blueorigamidigital/


Le jeu. 6 août 2020 à 10:11, OlivierWizi <notifications@github.com> a
écrit :
